name: firestore_converter_generator
description: >
  FirestoreConverter generates Firestore withConverter implementations for the annotated class.
version: 1.0.13
repository: https://github.com/Aurangseb/firestore_converter
issue_tracker: https://github.com/Aurangseb/firestore_converter/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  source_gen: ^2.0.0
  firestore_converter: ^1.0.9
  analyzer: ^7.3.0
  build: ^2.4.1

dev_dependencies:
  build_test: ^2.2.1
  build_runner: ^2.4.7
  test: ^1.24.0
  source_gen_test: ^1.0.6
